"""empty message

Revision ID: 18a4f8fb707b
Revises: a5e72f197c50
Create Date: 2025-03-12 11:32:46.598593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a4f8fb707b'
down_revision = 'a5e72f197c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint('reservations_id_fk_restaurant_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurant', ['id_fk_restaurant'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservations_id_fk_restaurant_fkey', 'restaurant', ['id_fk_restaurant'], ['id'])

    # ### end Alembic commands ###
