"""empty message

Revision ID: 267fa7b45297
Revises: d108f625ef03
Create Date: 2025-03-12 19:17:04.884695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267fa7b45297'
down_revision = 'd108f625ef03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
