"""empty message

Revision ID: 634a8c85bae1
Revises: 4d22efc5ec3e
Create Date: 2025-03-17 11:58:39.116311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634a8c85bae1'
down_revision = '4d22efc5ec3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fk_restaurant', sa.Integer(), nullable=False),
    sa.Column('id_fk_diner', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'ACCEPTED', 'REHUSED', 'CANCELED', name='reservationstate'), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fk_diner'], ['diner.id'], ),
    sa.ForeignKeyConstraint(['id_fk_restaurant'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
