"""empty message

Revision ID: a5e72f197c50
Revises: 57d495d9f749
Create Date: 2025-03-09 10:02:09.596166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e72f197c50'
down_revision = '57d495d9f749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fk_restaurant', sa.Integer(), nullable=False),
    sa.Column('id_fk_diner', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'ACCEPTED', 'REHUSED', 'CANCELED', name='reservationstate'), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fk_diner'], ['diner.id'], ),
    sa.ForeignKeyConstraint(['id_fk_restaurant'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diner', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('diner', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('reservations')
    # ### end Alembic commands ###
