"""empty message

Revision ID: be8110ad7395
Revises: 53e3896ff8d6
Create Date: 2025-03-21 20:19:05.148380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8110ad7395'
down_revision = '53e3896ff8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diner', schema=None) as batch_op:
        batch_op.drop_constraint('diner_fullname_key', type_='unique')
        batch_op.drop_constraint('diner_telephone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diner', schema=None) as batch_op:
        batch_op.create_unique_constraint('diner_telephone_key', ['telephone'])
        batch_op.create_unique_constraint('diner_fullname_key', ['fullname'])

    # ### end Alembic commands ###
