"""empty message

Revision ID: ce69adf609ed
Revises: 634a8c85bae1
Create Date: 2025-03-17 19:42:24.001768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce69adf609ed'
down_revision = '634a8c85bae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REHUSED', 'CANCELED', name='reservationstate'),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.String(length=120),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'REHUSED', 'CANCELED', name='reservationstate'),
               existing_nullable=False)

    # ### end Alembic commands ###
