"""empty message

Revision ID: eaaf486ac134
Revises: ee4a7fcc178b
Create Date: 2025-03-07 20:08:36.877175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaf486ac134'
down_revision = 'ee4a7fcc178b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('origin')
    # ### end Alembic commands ###
